import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.agent': 'Agent Service',
    'nav.redTeam': 'Red Team',
    'nav.requestDemo': 'Request Demo',
    
    // Hero Section
    'hero.badge': 'Enterprise LLM Security Platform',
    'hero.title': 'Test & Secure Your',
    'hero.titleHighlight': 'LLM Models',
    'hero.description': 'Comprehensive testing platform for Large Language Models with advanced security scanning, prompt sanitization, and vulnerability assessment in a controlled environment.',
    'hero.feature1': 'Advanced red-team security testing',
    'hero.feature2': 'Real-time prompt sanitization',
    'hero.feature3': 'Comprehensive performance analysis',
    'hero.startTesting': 'Start Testing Now',
    'hero.viewDemo': 'View Demo',
    'hero.redTeamTest': 'Red Team Test',
    'hero.vulnerabilityDetected': 'Vulnerability detected',
    'hero.blueTeamScan': 'Blue Team Scan',
    'hero.sanitizingPrompts': 'Sanitizing prompts...',
    'hero.agentAnalysis': 'Agent Analysis',
    'hero.performance': 'Performance: 94.2%',
    
    // Services Section
    'services.title': 'Comprehensive LLM Testing Services',
    'services.description': 'Our microservices architecture provides complete coverage for LLM security, performance, and reliability testing in enterprise environments.',
    'services.auth.title': 'Auth Service',
    'services.auth.description': 'Secure authentication and user registration with OAuth integration, JWT tokens, and multi-factor authentication.',
    'services.auth.feature1': 'OAuth Integration',
    'services.auth.feature2': 'MFA Support',
    'services.auth.feature3': 'JWT Tokens',
    'services.auth.feature4': 'Password Reset',
    'services.user.title': 'User Service',
    'services.user.description': 'Comprehensive user profile management with RBAC and GDPR compliance for enterprise security.',
    'services.user.feature1': 'Profile Management',
    'services.user.feature2': 'RBAC Controls',
    'services.user.feature3': 'GDPR Compliance',
    'services.user.feature4': 'Company Data',
    'services.redTeam.title': 'Red Team Service',
    'services.redTeam.description': 'Advanced negative testing to identify vulnerabilities and ensure your LLM handles malicious queries safely.',
    'services.redTeam.feature1': 'Negative Testing',
    'services.redTeam.feature2': 'Vulnerability Scanning',
    'services.redTeam.feature3': 'Bias Detection',
    'services.redTeam.feature4': 'Security Reports',
    'services.blueTeam.title': 'Blue Team Service',
    'services.blueTeam.description': 'Real-time prompt sanitization with advanced filtering to prevent harmful content from reaching your LLM.',
    'services.blueTeam.feature1': 'Prompt Sanitization',
    'services.blueTeam.feature2': 'Content Filtering',
    'services.blueTeam.feature3': 'Real-time Processing',
    'services.blueTeam.feature4': 'Traceability',
    'services.agent.title': 'Agent Service',
    'services.agent.description': 'Comprehensive LLM scanning and performance analysis with detailed reporting and improvement suggestions.',
    'services.agent.feature1': 'Performance Analysis',
    'services.agent.feature2': 'Capability Assessment',
    'services.agent.feature3': 'Response Time Metrics',
    'services.agent.feature4': 'Detailed Reports',
    'services.gateway.title': 'API Gateway',
    'services.gateway.description': 'Centralized entry point with intelligent routing, rate limiting, and comprehensive monitoring capabilities.',
    'services.gateway.feature1': 'Request Routing',
    'services.gateway.feature2': 'Rate Limiting',
    'services.gateway.feature3': 'Service Orchestration',
    'services.gateway.feature4': 'Monitoring',
    
    // Features Section
    'features.title': 'Why Choose LLMSecure?',
    'features.description': 'Built for enterprise requirements with uncompromising security, performance, and scalability.',
    'features.security.title': 'Enterprise Security',
    'features.security.description': 'End-to-end encryption, multi-factor authentication, and role-based access control for maximum security.',
    'features.security.stats': '99.9% Security Rating',
    'features.performance.title': 'High Performance',
    'features.performance.description': 'Sub-second response times with the ability to handle 10,000+ simultaneous testing requests.',
    'features.performance.stats': '<1s Response Time',
    'features.analytics.title': 'Advanced Analytics',
    'features.analytics.description': 'Comprehensive reporting with detailed insights into LLM performance, vulnerabilities, and improvements.',
    'features.analytics.stats': '50+ Metrics Tracked',
    'features.scalability.title': 'Global Scalability',
    'features.scalability.description': 'Horizontally scalable architecture deployed across multiple regions for optimal performance.',
    'features.scalability.stats': '99.99% Uptime',
    'features.realtime.title': 'Real-time Testing',
    'features.realtime.description': 'Continuous monitoring and real-time testing capabilities with instant vulnerability detection.',
    'features.realtime.stats': '24/7 Monitoring',
    'features.microservices.title': 'Microservices Architecture',
    'features.microservices.description': 'Modular, independently scalable services with robust communication and failover mechanisms.',
    'features.microservices.stats': '6 Core Services',
    'features.cta.title': 'Ready to Secure Your LLM Infrastructure?',
    'features.cta.description': 'Join leading enterprises who trust LLMSecure to test and secure their AI models.',
    'features.cta.button': 'Schedule a Demo',
    
    // Contact Section
    'contact.title': 'Ready to Get Started?',
    'contact.description': 'Schedule a demo or contact our team to learn how LLMSecure can protect and optimize your AI infrastructure.',
    'contact.info.title': 'Contact Information',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.office': 'Office',
    'contact.why.title': 'Why Choose LLMSecure?',
    'contact.why.feature1': 'Enterprise-grade security and compliance',
    'contact.why.feature2': '99.99% uptime with 24/7 support',
    'contact.why.feature3': 'Comprehensive testing in <1 second',
    'contact.why.feature4': 'Trusted by 50+ enterprise clients',
    'contact.form.title': 'Request a Demo',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.company': 'Company',
    'contact.form.role': 'Role',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Request Demo',
    'contact.form.submitted': 'Request Submitted!',
    'contact.form.placeholder.name': 'John Doe',
    'contact.form.placeholder.email': 'john@company.com',
    'contact.form.placeholder.company': 'Acme Corp',
    'contact.form.placeholder.message': 'Tell us about your LLM testing needs...',
    'contact.form.role.select': 'Select your role',
    'contact.form.role.security': 'Security Engineer',
    'contact.form.role.product': 'Product Manager',
    'contact.form.role.developer': 'Developer',
    'contact.form.role.cto': 'CTO',
    'contact.form.role.other': 'Other',
    
    // Footer
    'footer.description': 'Enterprise-grade LLM testing platform for security, performance, and reliability assessment.',
    'footer.services': 'Services',
    'footer.services.redTeam': 'Red Team Testing',
    'footer.services.blueTeam': 'Blue Team Sanitization',
    'footer.services.agent': 'Agent Analysis',
    'footer.services.audits': 'Security Audits',
    'footer.company': 'Company',
    'footer.company.about': 'About Us',
    'footer.company.careers': 'Careers',
    'footer.company.blog': 'Blog',
    'footer.company.press': 'Press',
    'footer.contact': 'Contact',
    'footer.copyright': '© 2025 LLMSecure. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    
    // Agent Service Page
    'agent.title': 'Agent Service - LLM Analysis',
    'agent.description': 'Upload your LLM model as a ZIP file and receive a comprehensive analysis report covering performance, capabilities, and improvement recommendations.',
    'agent.upload.title': 'Upload Your LLM Model',
    'agent.upload.description': 'Drag and drop your ZIP file here, or click to browse',
    'agent.upload.button': 'Choose ZIP File',
    'agent.upload.format': 'Supported format: ZIP files up to 100MB',
    'agent.upload.success': 'File Uploaded Successfully',
    'agent.upload.analyze': 'Start Analysis',
    'agent.upload.different': 'Upload Different File',
    'agent.analyzing.title': 'Analyzing Your LLM Model',
    'agent.analyzing.description': 'Our AI agents are performing comprehensive analysis including performance metrics, capability assessment, and security evaluation.',
    'agent.analyzing.extracting': 'Extracting model files...',
    'agent.analyzing.testing': 'Running performance tests...',
    'agent.analyzing.generating': 'Generating report...',
    'agent.complete.title': 'Analysis Complete!',
    'agent.complete.description': 'Your comprehensive LLM analysis report is ready for download.',
    'agent.complete.performance': 'Overall Performance',
    'agent.complete.security': 'Security Score',
    'agent.complete.response': 'Avg Response Time',
    'agent.complete.download': 'Download PDF Report',
    'agent.complete.another': 'Analyze Another Model',
    'agent.report.title': 'What\'s Included in Your Report',
    'agent.report.performance.title': 'Performance Analysis',
    'agent.report.performance.description': 'Detailed metrics on response time, accuracy, and throughput capabilities.',
    'agent.report.capability.title': 'Capability Assessment',
    'agent.report.capability.description': 'Evaluation of model strengths, limitations, and use case recommendations.',
    'agent.report.security.title': 'Security Evaluation',
    'agent.report.security.description': 'Identification of potential vulnerabilities and security recommendations.',
    'agent.report.improvement.title': 'Improvement Suggestions',
    'agent.report.improvement.description': 'Actionable recommendations for optimizing model performance.',
    
    // Red Team Page
    'redTeam.title': 'Red Team Security Testing',
    'redTeam.description': 'Comprehensive adversarial testing to identify vulnerabilities, biases, and security weaknesses in your LLM implementation through automated red team attacks.',
    'redTeam.api.title': 'API Configuration',
    'redTeam.api.description': 'Paste your cURL command below. We\'ll extract the endpoint and parameters for testing.',
    'redTeam.api.placeholder': 'Paste your cURL command here...',
    'redTeam.api.security.title': 'Security Notice',
    'redTeam.api.security.description': 'Ensure you have proper authorization to test this endpoint. All tests are logged for security purposes.',
    'redTeam.results.title': 'Test Results',
    'redTeam.results.configure': 'Configure your API and select tests to see results here',
    'redTeam.results.running': 'Running Security Tests',
    'redTeam.results.executing': 'Executing {count} adversarial tests...',
    'redTeam.results.vulnerabilities': 'Vulnerabilities',
    'redTeam.results.warnings': 'Warnings',
    'redTeam.results.riskScore': 'Risk Score',
    'redTeam.results.download': 'Download Security Report',
    'redTeam.selection.title': 'Security Test Selection',
    'redTeam.selection.selected': '{count} tests selected',
    'redTeam.selection.selectAll': 'Select All',
    'redTeam.selection.deselectAll': 'Deselect All',
    'redTeam.selection.run': 'Run {count} Security Tests',
    'redTeam.selection.running': 'Running Tests...',
    'redTeam.category.promptInjection': 'Prompt Injection',
    'redTeam.category.bias': 'Bias & Fairness',
    'redTeam.category.harmful': 'Harmful Content',
    'redTeam.category.privacy': 'Privacy & Security',
    'redTeam.test.promptInjectionBasic': 'Basic Prompt Injection',
    'redTeam.test.promptInjectionBasic.desc': 'Tests for simple prompt injection vulnerabilities',
    'redTeam.test.promptInjectionAdvanced': 'Advanced Prompt Injection',
    'redTeam.test.promptInjectionAdvanced.desc': 'Complex multi-step injection attempts',
    'redTeam.test.systemPromptLeak': 'System Prompt Leakage',
    'redTeam.test.systemPromptLeak.desc': 'Attempts to extract system prompts',
    'redTeam.test.genderBias': 'Gender Bias Detection',
    'redTeam.test.genderBias.desc': 'Tests for gender-based biases in responses',
    'redTeam.test.racialBias': 'Racial Bias Detection',
    'redTeam.test.racialBias.desc': 'Tests for racial and ethnic biases',
    'redTeam.test.ageBias': 'Age Bias Detection',
    'redTeam.test.ageBias.desc': 'Tests for age-related biases',
    'redTeam.test.violenceContent': 'Violence Content',
    'redTeam.test.violenceContent.desc': 'Tests for violent content generation',
    'redTeam.test.hateSpeech': 'Hate Speech',
    'redTeam.test.hateSpeech.desc': 'Tests for hate speech generation',
    'redTeam.test.misinformation': 'Misinformation',
    'redTeam.test.misinformation.desc': 'Tests for spreading false information',
    'redTeam.test.piiExtraction': 'PII Extraction',
    'redTeam.test.piiExtraction.desc': 'Attempts to extract personal information',
    'redTeam.test.dataPoisoning': 'Data Poisoning',
    'redTeam.test.dataPoisoning.desc': 'Tests for data poisoning vulnerabilities',
    'redTeam.test.modelInversion': 'Model Inversion',
    'redTeam.test.modelInversion.desc': 'Attempts to reverse-engineer training data',
  },
  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.agent': 'خدمة الوكيل',
    'nav.redTeam': 'الفريق الأحمر',
    'nav.requestDemo': 'طلب عرض توضيحي',
    
    // Hero Section
    'hero.badge': 'منصة أمان نماذج اللغة للمؤسسات',
    'hero.title': 'اختبر وأمّن',
    'hero.titleHighlight': 'نماذج اللغة الخاصة بك',
    'hero.description': 'منصة اختبار شاملة لنماذج اللغة الكبيرة مع مسح أمني متقدم وتنظيف المطالبات وتقييم الثغرات في بيئة محكومة.',
    'hero.feature1': 'اختبار أمني متقدم للفريق الأحمر',
    'hero.feature2': 'تنظيف المطالبات في الوقت الفعلي',
    'hero.feature3': 'تحليل أداء شامل',
    'hero.startTesting': 'ابدأ الاختبار الآن',
    'hero.viewDemo': 'عرض توضيحي',
    'hero.redTeamTest': 'اختبار الفريق الأحمر',
    'hero.vulnerabilityDetected': 'تم اكتشاف ثغرة',
    'hero.blueTeamScan': 'مسح الفريق الأزرق',
    'hero.sanitizingPrompts': 'تنظيف المطالبات...',
    'hero.agentAnalysis': 'تحليل الوكيل',
    'hero.performance': 'الأداء: 94.2%',
    
    // Services Section
    'services.title': 'خدمات اختبار نماذج اللغة الشاملة',
    'services.description': 'توفر بنيتنا المعمارية للخدمات المصغرة تغطية كاملة لأمان ونماذج اللغة وأدائها واختبار الموثوقية في بيئات المؤسسات.',
    'services.auth.title': 'خدمة المصادقة',
    'services.auth.description': 'مصادقة آمنة وتسجيل المستخدمين مع تكامل OAuth ورموز JWT والمصادقة متعددة العوامل.',
    'services.auth.feature1': 'تكامل OAuth',
    'services.auth.feature2': 'دعم MFA',
    'services.auth.feature3': 'رموز JWT',
    'services.auth.feature4': 'إعادة تعيين كلمة المرور',
    'services.user.title': 'خدمة المستخدم',
    'services.user.description': 'إدارة شاملة لملفات تعريف المستخدمين مع RBAC وامتثال GDPR لأمان المؤسسات.',
    'services.user.feature1': 'إدارة الملف الشخصي',
    'services.user.feature2': 'ضوابط RBAC',
    'services.user.feature3': 'امتثال GDPR',
    'services.user.feature4': 'بيانات الشركة',
    'services.redTeam.title': 'خدمة الفريق الأحمر',
    'services.redTeam.description': 'اختبار سلبي متقدم لتحديد الثغرات وضمان تعامل نموذج اللغة مع الاستعلامات الضارة بأمان.',
    'services.redTeam.feature1': 'الاختبار السلبي',
    'services.redTeam.feature2': 'مسح الثغرات',
    'services.redTeam.feature3': 'كشف التحيز',
    'services.redTeam.feature4': 'تقارير الأمان',
    'services.blueTeam.title': 'خدمة الفريق الأزرق',
    'services.blueTeam.description': 'تنظيف المطالبات في الوقت الفعلي مع تصفية متقدمة لمنع المحتوى الضار من الوصول إلى نموذج اللغة.',
    'services.blueTeam.feature1': 'تنظيف المطالبات',
    'services.blueTeam.feature2': 'تصفية المحتوى',
    'services.blueTeam.feature3': 'معالجة في الوقت الفعلي',
    'services.blueTeam.feature4': 'إمكانية التتبع',
    'services.agent.title': 'خدمة الوكيل',
    'services.agent.description': 'مسح شامل لنماذج اللغة وتحليل الأداء مع تقارير مفصلة واقتراحات للتحسين.',
    'services.agent.feature1': 'تحليل الأداء',
    'services.agent.feature2': 'تقييم القدرات',
    'services.agent.feature3': 'مقاييس وقت الاستجابة',
    'services.agent.feature4': 'تقارير مفصلة',
    'services.gateway.title': 'بوابة API',
    'services.gateway.description': 'نقطة دخول مركزية مع توجيه ذكي وتحديد المعدل وقدرات مراقبة شاملة.',
    'services.gateway.feature1': 'توجيه الطلبات',
    'services.gateway.feature2': 'تحديد المعدل',
    'services.gateway.feature3': 'تنسيق الخدمات',
    'services.gateway.feature4': 'المراقبة',
    
    // Features Section
    'features.title': 'لماذا تختار LLMSecure؟',
    'features.description': 'مبني لمتطلبات المؤسسات مع أمان وأداء وقابلية توسع لا تقبل التنازل.',
    'features.security.title': 'أمان المؤسسات',
    'features.security.description': 'تشفير من طرف إلى طرف ومصادقة متعددة العوامل وتحكم في الوصول القائم على الأدوار للحصول على أقصى أمان.',
    'features.security.stats': 'تقييم أمان 99.9%',
    'features.performance.title': 'أداء عالي',
    'features.performance.description': 'أوقات استجابة أقل من ثانية مع القدرة على التعامل مع أكثر من 10,000 طلب اختبار متزامن.',
    'features.performance.stats': 'وقت استجابة <1 ثانية',
    'features.analytics.title': 'تحليلات متقدمة',
    'features.analytics.description': 'تقارير شاملة مع رؤى مفصلة حول أداء نماذج اللغة والثغرات والتحسينات.',
    'features.analytics.stats': 'أكثر من 50 مقياس متتبع',
    'features.scalability.title': 'قابلية التوسع العالمية',
    'features.scalability.description': 'بنية قابلة للتوسع أفقياً منتشرة عبر مناطق متعددة للحصول على أداء مثالي.',
    'features.scalability.stats': 'وقت تشغيل 99.99%',
    'features.realtime.title': 'اختبار في الوقت الفعلي',
    'features.realtime.description': 'مراقبة مستمرة وقدرات اختبار في الوقت الفعلي مع كشف فوري للثغرات.',
    'features.realtime.stats': 'مراقبة 24/7',
    'features.microservices.title': 'بنية الخدمات المصغرة',
    'features.microservices.description': 'خدمات معيارية قابلة للتوسع بشكل مستقل مع آليات اتصال قوية وتجاوز الأخطاء.',
    'features.microservices.stats': '6 خدمات أساسية',
    'features.cta.title': 'هل أنت مستعد لتأمين بنية نماذج اللغة الخاصة بك؟',
    'features.cta.description': 'انضم إلى المؤسسات الرائدة التي تثق في LLMSecure لاختبار وتأمين نماذج الذكاء الاصطناعي الخاصة بها.',
    'features.cta.button': 'جدولة عرض توضيحي',
    
    // Contact Section
    'contact.title': 'هل أنت مستعد للبدء؟',
    'contact.description': 'جدول عرضاً توضيحياً أو اتصل بفريقنا لتتعلم كيف يمكن لـ LLMSecure حماية وتحسين بنية الذكاء الاصطناعي الخاصة بك.',
    'contact.info.title': 'معلومات الاتصال',
    'contact.email': 'البريد الإلكتروني',
    'contact.phone': 'الهاتف',
    'contact.office': 'المكتب',
    'contact.why.title': 'لماذا تختار LLMSecure؟',
    'contact.why.feature1': 'أمان وامتثال على مستوى المؤسسات',
    'contact.why.feature2': 'وقت تشغيل 99.99% مع دعم 24/7',
    'contact.why.feature3': 'اختبار شامل في أقل من ثانية واحدة',
    'contact.why.feature4': 'موثوق به من قبل أكثر من 50 عميل مؤسسي',
    'contact.form.title': 'طلب عرض توضيحي',
    'contact.form.name': 'الاسم الكامل',
    'contact.form.email': 'عنوان البريد الإلكتروني',
    'contact.form.company': 'الشركة',
    'contact.form.role': 'الدور',
    'contact.form.message': 'الرسالة',
    'contact.form.submit': 'طلب عرض توضيحي',
    'contact.form.submitted': 'تم إرسال الطلب!',
    'contact.form.placeholder.name': 'أحمد محمد',
    'contact.form.placeholder.email': 'ahmed@company.com',
    'contact.form.placeholder.company': 'شركة أكمي',
    'contact.form.placeholder.message': 'أخبرنا عن احتياجات اختبار نماذج اللغة الخاصة بك...',
    'contact.form.role.select': 'اختر دورك',
    'contact.form.role.security': 'مهندس أمان',
    'contact.form.role.product': 'مدير منتج',
    'contact.form.role.developer': 'مطور',
    'contact.form.role.cto': 'مدير تقني',
    'contact.form.role.other': 'أخرى',
    
    // Footer
    'footer.description': 'منصة اختبار نماذج اللغة على مستوى المؤسسات للأمان والأداء وتقييم الموثوقية.',
    'footer.services': 'الخدمات',
    'footer.services.redTeam': 'اختبار الفريق الأحمر',
    'footer.services.blueTeam': 'تنظيف الفريق الأزرق',
    'footer.services.agent': 'تحليل الوكيل',
    'footer.services.audits': 'تدقيق الأمان',
    'footer.company': 'الشركة',
    'footer.company.about': 'من نحن',
    'footer.company.careers': 'الوظائف',
    'footer.company.blog': 'المدونة',
    'footer.company.press': 'الصحافة',
    'footer.contact': 'اتصل بنا',
    'footer.copyright': '© 2025 LLMSecure. جميع الحقوق محفوظة.',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.cookies': 'سياسة ملفات تعريف الارتباط',
    
    // Agent Service Page
    'agent.title': 'خدمة الوكيل - تحليل نماذج اللغة',
    'agent.description': 'ارفع نموذج اللغة الخاص بك كملف ZIP واحصل على تقرير تحليل شامل يغطي الأداء والقدرات وتوصيات التحسين.',
    'agent.upload.title': 'ارفع نموذج اللغة الخاص بك',
    'agent.upload.description': 'اسحب وأفلت ملف ZIP هنا، أو انقر للتصفح',
    'agent.upload.button': 'اختر ملف ZIP',
    'agent.upload.format': 'التنسيق المدعوم: ملفات ZIP حتى 100 ميجابايت',
    'agent.upload.success': 'تم رفع الملف بنجاح',
    'agent.upload.analyze': 'بدء التحليل',
    'agent.upload.different': 'رفع ملف مختلف',
    'agent.analyzing.title': 'تحليل نموذج اللغة الخاص بك',
    'agent.analyzing.description': 'وكلاء الذكاء الاصطناعي لدينا يقومون بتحليل شامل يشمل مقاييس الأداء وتقييم القدرات وتقييم الأمان.',
    'agent.analyzing.extracting': 'استخراج ملفات النموذج...',
    'agent.analyzing.testing': 'تشغيل اختبارات الأداء...',
    'agent.analyzing.generating': 'إنشاء التقرير...',
    'agent.complete.title': 'اكتمل التحليل!',
    'agent.complete.description': 'تقرير تحليل نماذج اللغة الشامل جاهز للتنزيل.',
    'agent.complete.performance': 'الأداء العام',
    'agent.complete.security': 'نقاط الأمان',
    'agent.complete.response': 'متوسط وقت الاستجابة',
    'agent.complete.download': 'تنزيل تقرير PDF',
    'agent.complete.another': 'تحليل نموذج آخر',
    'agent.report.title': 'ما هو مدرج في تقريرك',
    'agent.report.performance.title': 'تحليل الأداء',
    'agent.report.performance.description': 'مقاييس مفصلة حول وقت الاستجابة والدقة وقدرات الإنتاجية.',
    'agent.report.capability.title': 'تقييم القدرات',
    'agent.report.capability.description': 'تقييم نقاط القوة والقيود في النموذج وتوصيات حالات الاستخدام.',
    'agent.report.security.title': 'تقييم الأمان',
    'agent.report.security.description': 'تحديد الثغرات المحتملة وتوصيات الأمان.',
    'agent.report.improvement.title': 'اقتراحات التحسين',
    'agent.report.improvement.description': 'توصيات قابلة للتنفيذ لتحسين أداء النموذج.',
    
    // Red Team Page
    'redTeam.title': 'اختبار أمان الفريق الأحمر',
    'redTeam.description': 'اختبار عدائي شامل لتحديد الثغرات والتحيزات ونقاط الضعف الأمنية في تنفيذ نماذج اللغة من خلال هجمات الفريق الأحمر الآلية.',
    'redTeam.api.title': 'تكوين API',
    'redTeam.api.description': 'الصق أمر cURL أدناه. سنستخرج نقطة النهاية والمعاملات للاختبار.',
    'redTeam.api.placeholder': 'الصق أمر cURL هنا...',
    'redTeam.api.security.title': 'إشعار أمني',
    'redTeam.api.security.description': 'تأكد من أن لديك التفويض المناسب لاختبار نقطة النهاية هذه. جميع الاختبارات مسجلة لأغراض أمنية.',
    'redTeam.results.title': 'نتائج الاختبار',
    'redTeam.results.configure': 'قم بتكوين API واختر الاختبارات لرؤية النتائج هنا',
    'redTeam.results.running': 'تشغيل اختبارات الأمان',
    'redTeam.results.executing': 'تنفيذ {count} اختبار عدائي...',
    'redTeam.results.vulnerabilities': 'الثغرات',
    'redTeam.results.warnings': 'التحذيرات',
    'redTeam.results.riskScore': 'نقاط المخاطر',
    'redTeam.results.download': 'تنزيل تقرير الأمان',
    'redTeam.selection.title': 'اختيار اختبار الأمان',
    'redTeam.selection.selected': '{count} اختبار محدد',
    'redTeam.selection.selectAll': 'تحديد الكل',
    'redTeam.selection.deselectAll': 'إلغاء تحديد الكل',
    'redTeam.selection.run': 'تشغيل {count} اختبار أمان',
    'redTeam.selection.running': 'تشغيل الاختبارات...',
    'redTeam.category.promptInjection': 'حقن المطالبات',
    'redTeam.category.bias': 'التحيز والعدالة',
    'redTeam.category.harmful': 'المحتوى الضار',
    'redTeam.category.privacy': 'الخصوصية والأمان',
    'redTeam.test.promptInjectionBasic': 'حقن المطالبات الأساسي',
    'redTeam.test.promptInjectionBasic.desc': 'اختبارات لثغرات حقن المطالبات البسيطة',
    'redTeam.test.promptInjectionAdvanced': 'حقن المطالبات المتقدم',
    'redTeam.test.promptInjectionAdvanced.desc': 'محاولات حقن معقدة متعددة الخطوات',
    'redTeam.test.systemPromptLeak': 'تسريب مطالبة النظام',
    'redTeam.test.systemPromptLeak.desc': 'محاولات لاستخراج مطالبات النظام',
    'redTeam.test.genderBias': 'كشف التحيز الجنسي',
    'redTeam.test.genderBias.desc': 'اختبارات للتحيزات القائمة على الجنس في الردود',
    'redTeam.test.racialBias': 'كشف التحيز العرقي',
    'redTeam.test.racialBias.desc': 'اختبارات للتحيزات العرقية والإثنية',
    'redTeam.test.ageBias': 'كشف التحيز العمري',
    'redTeam.test.ageBias.desc': 'اختبارات للتحيزات المرتبطة بالعمر',
    'redTeam.test.violenceContent': 'محتوى العنف',
    'redTeam.test.violenceContent.desc': 'اختبارات لتوليد المحتوى العنيف',
    'redTeam.test.hateSpeech': 'خطاب الكراهية',
    'redTeam.test.hateSpeech.desc': 'اختبارات لتوليد خطاب الكراهية',
    'redTeam.test.misinformation': 'المعلومات المضللة',
    'redTeam.test.misinformation.desc': 'اختبارات لنشر معلومات خاطئة',
    'redTeam.test.piiExtraction': 'استخراج المعلومات الشخصية',
    'redTeam.test.piiExtraction.desc': 'محاولات لاستخراج المعلومات الشخصية',
    'redTeam.test.dataPoisoning': 'تسميم البيانات',
    'redTeam.test.dataPoisoning.desc': 'اختبارات لثغرات تسميم البيانات',
    'redTeam.test.modelInversion': 'انعكاس النموذج',
    'redTeam.test.modelInversion.desc': 'محاولات للهندسة العكسية لبيانات التدريب',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};